### ISSUE TITLE
pyRDDLGym-rl not compatible with pyRDDLGym 2.1

### ISSUE THREAD

**Issue by nhuet** [pyrddlgym-project/pyRDDLGym-rl#6]
When using last version of pyRDDLGym (2.1), we cannot import `SimplifiedActionRDDLEnv`:

```python
from pyRDDLGym_rl.core.env import SimplifiedActionRDDLEnv
```
returns
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nolwen/.cache/pypoetry/virtualenvs/scikit-decide-BNuSjA5L-py3.10/lib/python3.10/site-packages/pyRDDLGym_rl/core/env.py", line 18, in <module>
    from pyRDDLGym.core.seeding import RDDLEnvSeeder, RDDLEnvSeederFibonacci
ModuleNotFoundError: No module named 'pyRDDLGym.core.seeding'
```

**Comment by mike-gimelfarb** [comment]
Hi,

Apologies for the late follow up here. It seems you are using an old version of pyRDDLGym-rl that is not compatible with version 2.1 of pyRDDLGym. The seeding package was removed after version 1.4.4. You can either use the older pyRDDLGym, or the recommended option of updating pyRDDLGym-rl.

I have just checked that the latest versions work with both packages together, i.e.:

```
conda create -n rlenv python==3.11
conda activate rlenv
pip install stable-baselines3
pip install rddlrepository pyRDDLGym-rl
python -m pyRDDLGym_rl.examples.run_stable_baselines Cartpole_Continuous_gym 0 ppo
```

What commands did you use to install pyRDDLGym? It should install automatically if you pip install pyRDDLGym-rl.  Do you have any additional codes that would help us to reproduce the error? Let me know if you're experiencing further problems with install.

**Comment by mike-gimelfarb** [comment]
Hi again,

Ok my apologies, this one is on us! It seems the version on pypi is lagging behind the github version. My tests were done on the local/github copy.
An updated version (version 0.2) will be available soon.

**Comment by mike-gimelfarb** [comment]
Hi,
The issue should be fixed. You can find the newest version [here](https://pypi.org/project/pyRDDLGym-rl/0.2/).

**Comment by nhuet** [comment]
Thanks

**Comment by nhuet** [comment]
Actually, this only partially solves my issue. It is not working on python 3.12 because pyRDDLGym 2.1 requires python<3.12, thus on python 3.12, pyRDDLGym 2.0 installs which is not compatible with pyRDDLGym-rl 0.2... But i guess this is more of an issue for pyRDDLGym.

**Comment by nhuet** [comment]
Actually, this is another issue also for pyRDDLGym-rl: pyRDDLGym-rl 0.2 is not compatible with pyRDDLGym 2.0, even though it is said to be so.

The error is now (when calling 'SimplifiedActionRDDLEnv.reset()'):

```
E           AttributeError: 'SimplifiedActionRDDLEnv' object has no attribute 'seeds'. Did you mean: 'seed'?
```

Probably that setup.py should be updated with 
```
        install_requires=[
          'pyRDDLGym>=2.1'
        ],
```
